spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      maximum-pool-size: 2
      connection-timeout: 20000
  flyway:
    baseline-on-migrate: true
    clean-disabled: true
    encoding: UTF-8
    table: schema_version
    generate-ddl: true
    generate-ddl-auto: update
  jpa:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env[.properties]

management:
  endpoints:
    web:
      exposure:
        include: health

retroboard:
  jwt:
    secret: secret

server:
  error:
    include-stacktrace: never

firebase:
  signInWithPasswordUrl: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=
database:
  urlWithCredentials: postgres://compose:compose@localhost:5432/compose