spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://db:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres
  flyway:
    baseline-on-migrate: true
    clean-disabled: true
    encoding: UTF-8
    password: ${spring.datasource.password}
    table: schema_version
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    generate-ddl: true
    generate-ddl-auto: update
  jpa:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env[.properties]

retroboard:
  jwt:
    secret: secret

