spring:
  main:
    allow-bean-definition-overriding: true
  profile:
    active: production
  datasource:
    url: jdbc:postgresql://localhost:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres
    hikari:
      maximum-pool-size: 2
      connection-timeout: 20000

  flyway:
    baseline-on-migrate: true
    clean-disabled: true
    encoding: UTF-8
    password: ${spring.datasource.password}
    table: schema_version
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    generate-ddl: true
    generate-ddl-auto: update
  jpa:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env[.properties]

retroboard:
  jwt:
    secret: secret

server:
  error:
    include-stacktrace: never

firebase:
  signInWithPasswordUrl: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=
